<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\package.props" />
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Version>$(VersionBase).0-alpha</Version>
    <PackageId>MyDeltas.OpenApi</PackageId>
    <Description>MyDelta的ApiSchema转化器</Description>
    <PackageTags>MyDelta;OpenApi</PackageTags>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyDeltas\MyDeltas.csproj" />
  </ItemGroup>

</Project>
